---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pitstop-namespace
  name: logserver
  labels:
    app: logserver
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: logserver
  template:
    metadata:
      labels:
        app: logserver
    spec:
      containers:
        - name: logserver
          image: datalust/seq:latest
          ports:
            - containerPort: 5341
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"

---
apiVersion: v1
kind: Service
metadata:
  name: log-svc
  namespace: pitstop-namespace
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5341
  selector:
      app: logserver



