---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pitstop-namespace
  name: mailserver
  labels:
    app: mailserver
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
        - name: mailserver
          image: maildev/maildev:1.1.0
          ports:
            - containerPort: 25
              protocol: TCP
            - containerPort: 4000
              protocol: TCP
          
---
apiVersion: v1
kind: Service
metadata:
  name: mail-svc
  namespace: pitstop-namespace
spec:
  type: NodePort
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      nodePort: 30005
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30004
  selector:
      app: mailserver

