apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceserver
  annotations:
    kubernetes.io/change-cause: 'FirstVersion'
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: invoice-server
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: invoice-server
    spec:
      containers:
        - image: pitstop/invoiceservice:1.0
          name: invoiceservice
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
          resources:
            limits:
              memory: 512Mi
              cpu: 250m


      



