---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: pitstop-namespace
data:
  RABBITMQ_CONFIG_FILE: /etc/pitstop/rabbitmq.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-config
  namespace: pitstop-namespace
data:
   ACCEPT_EULA: "Y"
   MSSQL_PID: Developer
   SA_PASSWORD: 8jkGh47hnDw89Haq8LN2