---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    app: rabbitmq
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      spec:
        containers:
          - name: rabbitmq
            image: abbitmq:3-management-alpine
            ports:
              - containerPort: 15672
                protocol: Tcp
              - containerPort: 5672
            env:
              - name: RABBITMQ_CONFIG_FILE
                value: /etc/pitstop/rabbitmq.conf
            volumeMounts:
              - name: rabbitmq-data
                mountPath: /var/lib/rabbitmq
              - name: rabbitmq-config
                mountPath: /etc/pitstop
      
      namespace: 
        name: pitstop-namespace
        volumes: 
        - name: rabbitmq-data
          emptyDir: {} # Replace with a PersistentVolumeClaim for persistent storage
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 15672
    targetPort: 15672
    name: management-ui
  - port: 5672
    targetPort: 5672
    name: amqp
  selector:
    app: rabbitmq
  type: ClusterIP