---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq-svc
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - name: rabbitmqdata
              mountPath: /var/lib/rabbitmq 
            - name: rabbitmq-config
              mountPath:  /etc/pitstop/ 
              
  volumeClaimTemplates:
    - metadata:
        name: rabbitmqdata
      spec:
        accessModes: ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: rabbitmq-config
      spec:
        accessModes: ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

